version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      gha-bump:
        applies-to: version-updates
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: quarterly
    groups:
      all:
        applies-to: version-updates
        patterns:
          - "*"
